#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'hacker
        hostname: ubuntu-desktop
        username: hackerdevel
        password: '$y$j9T$ZbLTA2.19tkRVL/E3uzXq.$K/e./556eOhrHG3eYop0terEUwFmbj13Jc0LVJQ9jZ0'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:        
        - libreoffice      
        - wget
    snaps:
        - name: spotify
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
